port: 9949
endpoint: wss://bifrost-rpc.dwellir.com
mock-signature-host: true
db: ./bifrost.db.sqlite

import-storage:
  System:
    Account:
      - - - 5Gxk3eGqEcMGR96XFoeJd3pdo2G5uUwzFszbGg8jvS7PDnnR
        - data:
            free: 1000000000000000 # 1K BNC
  Tokens:
    Accounts:
      - - - 5Gxk3eGqEcMGR96XFoeJd3pdo2G5uUwzFszbGg8jvS7PDnnR
          - vtoken: KSM
        - free: 1000000000000000 # 1K vKSM
      - - - 5Gxk3eGqEcMGR96XFoeJd3pdo2G5uUwzFszbGg8jvS7PDnnR
          - vtoken: BNC
        - free: 1000000000000000 # 1K vBNC
      - - - 5Gxk3eGqEcMGR96XFoeJd3pdo2G5uUwzFszbGg8jvS7PDnnR
          - vtoken: MOVR
        - free: '1000000000000000000000' # 1K vMOVR
      - - - 5Gxk3eGqEcMGR96XFoeJd3pdo2G5uUwzFszbGg8jvS7PDnnR
          - vstoken: KSM
        - free: 1000000000000000 # 1K vsKSM
      - - - 5Gxk3eGqEcMGR96XFoeJd3pdo2G5uUwzFszbGg8jvS7PDnnR
          - token: ZLK
        - free: '1000000000000000000000' # 1K ZLK
  Council:
    Members: [5Gxk3eGqEcMGR96XFoeJd3pdo2G5uUwzFszbGg8jvS7PDnnR]
